import { useMemo } from "react";
import { useTranslation } from "react-i18next";
import { css } from "@emotion/css";
import { classNames } from "@sito/dashboard-app";

// icons
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";

// @sito/dashboard-app
import { Chip } from "@sito/dashboard-app";

// components
import { ItemCard, ItemCardTitle } from "components";
import { Autogenerated } from "./Autogenerated/Autogenerated";

// types
import type { TransactionCategoryCardPropsType } from "../types";

// lib
import { TransactionType } from "lib";

// utils
import { icons } from "../../Transactions/components/utils";

import "./styles.css";

export function TransactionCategoryCard(
  props: TransactionCategoryCardPropsType,
) {
  const { t } = useTranslation();

  const {
    id,
    onClick,
    onSelect,
    onLongPress,
    selectionMode,
    selected,
    actions,
    name,
    description,
    type,
    deletedAt,
    color,
    auto,
  } = props;
  const deleted = !!deletedAt;
  const typeValue = type ?? TransactionType.Out;

  const parsedDescription = useMemo(() => {
    if (!description?.length) return t("_entities:base.description.empty");
    if (auto) return t("_entities:transactionCategory.description.init");
    return description;
  }, [description, auto, t]);

  const typeTranslation = t(
    `_entities:transactionCategory.type.values.${String(
      TransactionType[typeValue],
    )}`,
  );

  return (
    <ItemCard
      title={
        <div className="transaction-category-card-title-row">
          {auto ? (
            <Autogenerated />
          ) : (
            <ItemCardTitle>
              {color ? (
                <span
                  className={classNames(
                    "transaction-category-card-color-dot",
                    css({ backgroundColor: color }),
                  )}
                ></span>
              ) : (
                ""
              )}
              {name}
            </ItemCardTitle>
          )}
          <Chip
            className={classNames(
              "transaction-category-card-mobile-type",
              typeValue === TransactionType.In
                ? "transaction-category-card-mobile-type--income"
                : "transaction-category-card-mobile-type--expense",
            )}
            textClassName="transaction-category-card-mobile-type-text"
            text={
              <>
                <FontAwesomeIcon
                  icon={icons[typeValue as keyof typeof icons]}
                />
                <span className="transaction-category-card-mobile-type-label">
                  {typeTranslation}
                </span>
              </>
            }
          />
        </div>
      }
      deleted={deleted}
      name={t("_pages:transactionCategory.forms.edit")}
      aria-label={t("_pages:transactionCategory.forms.editAria")}
      onClick={() => onClick(id)}
      selectionMode={selectionMode}
      selected={selected}
      onToggleSelection={() => onSelect?.(id)}
      onLongPressSelection={() => onLongPress?.(id)}
      actions={actions}
      className="transaction-category-card-content"
      containerClassName="transaction-category-card-container"
    >
      <p
        className={classNames(
          "transaction-category-card-description",
          !description && "transaction-category-card-description--empty",
          deleted && "transaction-category-card-description--deleted",
        )}
      >
        {parsedDescription}
      </p>
      <div className="chip-container transaction-category-card-desktop-type">
        <Chip
          className={typeValue === TransactionType.In ? "success" : "error"}
          text={
            <div className="transaction-category-card-desktop-type-text">
              <FontAwesomeIcon icon={icons[typeValue as keyof typeof icons]} />
              {typeTranslation}
            </div>
          }
        />
      </div>
    </ItemCard>
  );
}
