import { useMemo } from "react";
import { useTranslation } from "react-i18next";

// icons
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";

// @sito/dashboard-app
import { Chip } from "@sito/dashboard-app";

// components
import { ItemCard, ItemCardTitle } from "components";
import { Autogenerated } from "./Autogenerated/Autogenerated";

// types
import { TransactionCategoryCardPropsType } from "../types";

// lib
import { TransactionType } from "lib";

// utils
import { icons } from "../../Transactions/components/utils";

export function TransactionCategoryCard(
  props: TransactionCategoryCardPropsType,
) {
  const { t } = useTranslation();

  const { id, onClick, actions, name, description, type, deletedAt, auto } =
    props;
  const deleted = !!deletedAt;
  const typeValue = type ?? TransactionType.Out;

  const parsedDescription = useMemo(() => {
    if (!description?.length) return t("_entities:base.description.empty");
    if (auto) return t("_entities:transactionCategory.description.init");
    return description;
  }, [description, auto, t]);

  const typeClassName =
    typeValue === TransactionType.In
      ? "bg-bg-success/10 !text-bg-success border-bg-success/30"
      : "bg-bg-error/10 !text-bg-error border-bg-error/30";
  const typeTranslation = t(
    `_entities:transactionCategory.type.values.${String(
      TransactionType[typeValue],
    )}`,
  );

  return (
    <ItemCard
      title={
        <div className="flex w-full items-start justify-between gap-2">
          {auto ? (
            <Autogenerated />
          ) : (
            <ItemCardTitle className="max-sm:text-sm">{name}</ItemCardTitle>
          )}
          <Chip
            className={`sm:!hidden max-xs:inline-flex shrink-0 items-center justify-center gap-1 rounded-full border !px-2 !py-1 text-xs max-xs:px-1.5 max-xs:py-0.5 ${typeClassName}`}
            textClassName="flex gap-2 items-center justify-center text-xs"
            text={
              <>
                <FontAwesomeIcon
                  icon={icons[typeValue as keyof typeof icons]}
                />
                <span className="max-xs:hidden">{typeTranslation}</span>
              </>
            }
          />
        </div>
      }
      deleted={deleted}
      name={t("_pages:transactionCategory.forms.edit")}
      aria-label={t("_pages:transactionCategory.forms.editAria")}
      onClick={() => (!deleted ? onClick(id) : {})}
      actions={actions}
      className="gap-2 max-sm:gap-1"
      containerClassName="max-sm:min-h-0 max-sm:rounded-xl max-sm:p-2.5"
    >
      <p
        className={`${description ? "" : "!text-xs italic"} text-start mb-2 max-xs:mb-0 max-xs:w-full max-xs:overflow-hidden max-xs:text-ellipsis max-xs:whitespace-nowrap max-sm:!text-xs max-xs:text-text-muted ${
          deleted ? "!text-bg-error" : ""
        }`}
      >
        {parsedDescription}
      </p>
      <div className="chip-container max-sm:!hidden">
        <Chip
          className={typeValue === TransactionType.In ? "success" : "error"}
          text={
            <div className="flex gap-2 items-center justify-center">
              <FontAwesomeIcon icon={icons[typeValue as keyof typeof icons]} />
              {typeTranslation}
            </div>
          }
        />
      </div>
    </ItemCard>
  );
}
