import { useMemo } from "react";
import { useTranslation } from "react-i18next";

// @sito/dashboard
import { useTimeAge } from "@sito/dashboard-app";

// lib
import { TransactionType } from "lib";

// components
import { Currency } from "../../../Currencies";
import { Autogenerated, Type } from "../../../TransactionCategories";

// types
import { TransactionPropsType } from "./types";

export const Transaction = (props: TransactionPropsType) => {
  const { t } = useTranslation();

  const { description, initial, date, amount, category, currency } = props;

  const { timeAge } = useTimeAge();

  const parsedDescription = useMemo(() => {
    if (!description?.length) return t("_entities:base.description.empty");
    if (initial) return t("_entities:transactionCategory.description.init");
    return description;
  }, [description, initial, t]);

  const isIn = useMemo(() => category?.type === TransactionType.In, [category]);

  return (
    <li className={"rounded-lg bg-base-light p-2 pr-3 flex items-center gap-2 w-full"}>
      <Type
        className="bg-base-dark px-3 py-3.5 rounded-full"
        type={category?.type ?? TransactionType.In}
        filled={false}
        noText
      />
      <div className="flex flex-col items-start justify-start w-full">
        <div className="flex items-center gap-1 max-xs:!text-xs">
          {category?.initial ? (
            <Autogenerated isTitle={false} />
          ) : (
            <p>{category?.name}</p>
          )}
          <p className="lowercase">- {timeAge(new Date(date))}</p>
        </div>
        <p className="text-xs text-left">{parsedDescription}</p>
      </div>
      <p className="gap-1 text-nowrap">
        <span className="mr-1">
          {isIn ? "+ " : "- "}
          {amount}
        </span>
        <Currency {...currency} />
      </p>
    </li>
  );
};
