import { useMemo } from "react";
import { useTranslation } from "react-i18next";

// @sito/dashboard
import { useTimeAge } from "@sito/dashboard-app";

// lib
import {
  TransactionType,
  getPrimaryTransactionCategory,
  getTransactionCategories,
} from "lib";

// components
import { Currency } from "../../../Currencies";
import { Autogenerated, Type } from "../../../TransactionCategories";

// types
import type { TransactionPropsType } from "./types";

import "./styles.css";

export const Transaction = (props: TransactionPropsType) => {
  const { t } = useTranslation();

  const { description, auto, date, amount, currency } = props;

  const { timeAge } = useTimeAge();

  const parsedDescription = useMemo(() => {
    if (!description?.length) return t("_entities:base.description.empty");
    if (auto) return t("_entities:transactionCategory.description.init");
    return description;
  }, [description, auto, t]);

  const transactionCategories = useMemo(
    () => getTransactionCategories(props),
    [props],
  );

  const primaryCategory = useMemo(
    () => getPrimaryTransactionCategory(props),
    [props],
  );

  const parsedCategoryName = useMemo(() => {
    if (!transactionCategories.length) return "-";

    return transactionCategories
      .map((category) =>
        category.auto
          ? t("_entities:transactionCategory.name.init")
          : category.name,
      )
      .join(", ");
  }, [t, transactionCategories]);

  const hasAutogeneratedCategory = useMemo(
    () => transactionCategories.some((category) => category.auto),
    [transactionCategories],
  );

  const isIn = useMemo(
    () => primaryCategory?.type === TransactionType.In,
    [primaryCategory],
  );

  return (
    <li className="account-last-transaction">
      <Type
        className="account-last-transaction-type"
        type={primaryCategory?.type ?? TransactionType.In}
        filled={false}
        noText
      />
      <div className="account-last-transaction-body">
        <div className="account-last-transaction-meta">
          {hasAutogeneratedCategory ? (
            <Autogenerated isTitle={false} />
          ) : (
            <p>{parsedCategoryName}</p>
          )}
          <p className="lowercase">
            {date ? `- ${timeAge(new Date(date))}` : ""}
          </p>
        </div>
        <p className="account-last-transaction-description">
          {parsedDescription}
        </p>
      </div>
      <p className="account-last-transaction-amount">
        <span className="account-last-transaction-amount-value">
          {isIn ? "+ " : "- "}
          {amount}
        </span>
        <Currency {...currency} />
      </p>
    </li>
  );
};
