import { useMemo } from "react";
import { useTranslation } from "react-i18next";

// @sito/dashboard
import {
  FilterTypes,
  Option,
  enumToKeyValueArray,
  getFormattedDateTime,
  Error,
} from "@sito/dashboard-app";

// components
import { WalletTable } from "components";

// hooks
import { useTransactionsList } from "hooks";

// lib
import {
  EntityName,
  TransactionDto,
  TransactionType,
  useParseColumns,
} from "lib";

// types
import { TransactionContainerPropsType } from "./types";

// views
import { Currency } from "views/Currencies/components/Currency";
import { Autogenerated } from "views/TransactionCategories/components/Autogenerated";
import { Type } from "views/TransactionCategories/components/Type";

export const TransactionTable = (props: TransactionContainerPropsType) => {
  const { accountId, categories, getActions, showFilters, setShowFilters } =
    props;

  const { t } = useTranslation();

  const listFilters = useMemo(() => ({ accountId }), [accountId]);

  const { data, isLoading, error } = useTransactionsList({
    filters: listFilters,
  });

  // #region columns

  const renderEmpty = (value: string | undefined | null) => {
    if (value && value.length) {
      return value;
    }
    return t("_entities:base.description.empty");
  };

  const columnDefs = useMemo(
    () => [
      {
        key: "category",
        label: t("_entities:transaction.category.label"),
        filterOptions: {
          type: FilterTypes.autocomplete,
          defaultValue: [],
          options: categories,
          placeholder: t("_entities:transaction.category.placeholder"),
        },
        renderBody: (_value: unknown, entity: TransactionDto) =>
          entity.category?.auto ? (
            <Autogenerated isTitle={false} />
          ) : (
            entity.category?.name
          ),
      },
      {
        key: "amount",
        filterOptions: { type: FilterTypes.number },
        renderBody: (value: unknown, entity: TransactionDto) => {
          const amount = typeof value === "number" ? value : Number(value) || 0;
          return (
            <p>
              {entity?.category?.type === TransactionType.Out ? "- " : ""}
              {amount}{" "}
              <Currency
                name={entity.account?.currency?.name}
                symbol={entity.account?.currency?.symbol}
              />
            </p>
          );
        },
      },
      {
        key: "type",
        label: t("_entities:transactionCategory.type.label"),
        filterOptions: {
          multiple: false,
          type: FilterTypes.autocomplete,
          placeholder: t("_entities:transactionCategory.type.placeholder"),
          options: enumToKeyValueArray(TransactionType)?.map((item) => ({
            id: item.value,
            value: t(`_entities:transactionCategory:type.values.${item.key}`),
          })) as Option[],
        },
        renderBody: (_: unknown, entity: TransactionDto) => (
          <div className="w-fit">
            <Type type={entity?.category?.type ?? TransactionType.In} />
          </div>
        ),
      },
      {
        key: "description",
        label: t("_entities:base.description.label"),
        filterOptions: {
          type: FilterTypes.text,
          placeholder: t("_entities:base.description.placeholder"),
        },
        renderBody: (value: unknown, entity: TransactionDto) => (
          <span className="truncate">
            {entity.auto
              ? t("_entities:transactionCategory.name.init")
              : renderEmpty(
                  typeof value === "string" || value == null
                    ? value
                    : String(value),
                )}
          </span>
        ),
      },
      {
        key: "date",
        filterOptions: { type: FilterTypes.date },
        renderBody: (value: unknown) => (
          <p>{getFormattedDateTime(String(value ?? ""))}</p>
        ),
      },
    ],
    // eslint-disable-next-line react-hooks/exhaustive-deps
    [categories, t],
  );

  const toIgnore = useMemo(() => ["id", "createdAt", "updatedAt"], []);

  const { columns } = useParseColumns<TransactionDto>(
    columnDefs,
    EntityName.Transaction,
    toIgnore,
  );

  const filterOptions = useMemo(
    () => ({
      button: { hide: true as const },
      dropdown: setShowFilters
        ? { opened: showFilters ?? false, setOpened: setShowFilters }
        : undefined,
    }),
    [showFilters, setShowFilters],
  );

  // #endregion

  return error ? (
    <Error error={error} />
  ) : (
    <WalletTable
      total={data?.totalElements ?? 0}
      data={data?.items ?? []}
      actions={getActions}
      isLoading={isLoading}
      entity={EntityName.Transaction}
      columns={columns}
      contentClassName="transactions-table-body base-border"
      filterOptions={filterOptions}
    />
  );
};
