import { useTranslation } from "react-i18next";

// icons
import { faMagicWandSparkles } from "@fortawesome/free-solid-svg-icons";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { classNames } from "@sito/dashboard-app";

// components
import { ItemCardTitle } from "components";

// types
import type { AutogeneratedPropsType } from "./types";

import "./styles.css";

export const Autogenerated = (props: AutogeneratedPropsType) => {
  const { t } = useTranslation();

  const { isTitle = true, onlyIcon = false } = props;

  const textValue = t("_entities:transactionCategory.name.init");

  const Component = isTitle ? ItemCardTitle : "span";

  return (
    <div className="transaction-category-autogenerated">
      <FontAwesomeIcon
        className={classNames(
          !onlyIcon && "transaction-category-autogenerated-icon--with-text",
        )}
        icon={faMagicWandSparkles}
        data-tooltip-id="tooltip"
        data-tooltip-content={t("_accessibility:labels.autogenerated")}
      />
      {!onlyIcon && <Component>{textValue}</Component>}
    </div>
  );
};
