import { useTranslation } from "react-i18next";

// icons
import { faMagicWandSparkles } from "@fortawesome/free-solid-svg-icons";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";

// components
import { ItemCardTitle } from "components";

// types
import { AutogeneratedPropsType } from "./types";

export const Autogenerated = (props: AutogeneratedPropsType) => {
  const { t } = useTranslation();

  const { isTitle = true, onlyIcon = false } = props;

  const textValue = t("_entities:transactionCategory.name.init");

  const Component = isTitle ? ItemCardTitle : "span";

  return (
    <div className="flex gap-2 items-center justify-start">
      <FontAwesomeIcon
        className={onlyIcon ? "" : "max-xs:!hidden"}
        icon={faMagicWandSparkles}
        data-tooltip-id="tooltip"
        data-tooltip-content={t("_accessibility:labels.autogenerated")}
      />
      {!onlyIcon && <Component>{textValue}</Component>}
    </div>
  );
};
