import { useTranslation } from "react-i18next";

// icons
import { faMagicWandSparkles } from "@fortawesome/free-solid-svg-icons";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";

// components
import { ItemCardTitle } from "components";

// types
import { AutogneratedPropsType } from "./types";

const Autogenerated = (props: AutogneratedPropsType) => {
  const { t } = useTranslation();

  const { isTitle = true } = props;

  const textValue = t("_entities:transactionCategory.name.init");

  return (
    <div className="flex gap-2 items-center justify-start">
      <FontAwesomeIcon
        icon={faMagicWandSparkles}
        data-tooltip-id="tooltip"
        data-tooltip-content={t("_accessibility:labels.autogenerated")}
      />

      {isTitle ? (
        <ItemCardTitle>{textValue}</ItemCardTitle>
      ) : (
        <p>{textValue}</p>
      )}
    </div>
  );
};

export default Autogenerated;
