import { useMemo } from "react";
import { useTranslation } from "react-i18next";

// @sito/dashboard
import { Chip } from "@sito/dashboard";

// components
import { ItemCard } from "components";

// types
import { TransactionCardPropsType } from "../types";

// hooks
import { useTimeAge } from "hooks";

// views
import { Currency, Autogenerated, Type } from "views";

// lib
import { TransactionType } from "lib";

export function TransactionCard(props: TransactionCardPropsType) {
  const { t } = useTranslation();

  const {
    id,
    onClick,
    actions,
    description,
    initial,
    date,
    amount,
    category,
    account,
    deleted,
  } = props;

  const { timeAge } = useTimeAge();

  const parsedDescription = useMemo(() => {
    if (!description?.length) return t("_entities:base.description.empty");
    if (initial) return t("_entities:transactionCategory.description.init");
    return description;
  }, [description, initial, t]);

  return (
    <ItemCard
      title={category?.initial ? <Autogenerated /> : category?.name}
      deleted={deleted}
      name={t("_pages:accounts.forms.edit")}
      aria-label={t("_pages:accounts.forms.editAria")}
      onClick={() => (!deleted ? onClick(id) : {})}
      actions={actions}
    >
      <p
        className={`${description ? "" : "!text-xs italic"} text-start mb-2 ${
          deleted ? "!text-secondary" : ""
        }`}
      >
        {parsedDescription}
      </p>
      <div className="chip-container">
        <Type type={category?.type ?? TransactionType.In} />
        <Chip
          label={
            <>
              {amount}{" "}
              <Currency
                name={account?.currency?.name}
                symbol={account?.currency?.symbol}
              />
            </>
          }
        />
        <Chip label={timeAge(new Date(date))} />
      </div>
    </ItemCard>
  );
}
