import { useEffect, useMemo } from "react";
import { useTranslation } from "react-i18next";
import { Controller, useWatch } from "react-hook-form";

// @sito/dashboard-app
import {
  FormDialog,
  ParagraphInput,
  TextInput,
  Option,
  AutocompleteInput,
} from "@sito/dashboard-app";

// types
import {
  AddTransactionDialogPropsType,
  TransactionFormPropsType,
  EditTransactionDialogPropsType,
} from "../types";

// lib
import {
  CommonTransactionCategoryDto,
  Tables,
  hasMixedTransactionCategoryTypes,
  normalizeSelectedTransactionCategories,
} from "lib";

// hooks
import { useAccountsCommon, useTransactionCategoriesCommon } from "hooks";
import { Autogenerated } from "views/TransactionCategories";

export function TransactionForm(props: TransactionFormPropsType) {
  const {
    control,
    account,
    open,
    isLoading,
    setValue,
    lockCategory = false,
    lockAccount = false,
  } = props;
  const { t } = useTranslation();

  // #region external entities

  const accounts = useAccountsCommon();

  const accountOptions = useMemo(
    () => [...(accounts?.data ?? [])] as Option[],
    [accounts.data],
  );

  const categories = useTransactionCategoriesCommon();

  const categoryOptions = useMemo(
    () =>
      [
        ...(categories?.data?.map((category) => ({
          ...category,
          name: category.auto
            ? t("_entities:transactionCategory.name.init")
            : category.name,
        })) ?? []),
      ] as CommonTransactionCategoryDto[],
    [categories?.data, t],
  );

  const selectedCategories = useWatch({
    control,
    name: "categories",
  }) as CommonTransactionCategoryDto[] | undefined;

  const selectedCategoryType = selectedCategories?.[0]?.type;

  const categoryOptionsByType = useMemo(() => {
    if (selectedCategoryType === undefined) return categoryOptions;

    return categoryOptions.filter(
      (category) => category.type === selectedCategoryType,
    );
  }, [categoryOptions, selectedCategoryType]);

  // #endregion

  useEffect(() => {
    if (account && setValue) setValue("account", account);
  }, [open, account, setValue]);

  const auto = useWatch({ control, name: "auto" });

  return (
    <>
      <Controller
        control={control}
        render={({ field }) => <input {...field} type="hidden" />}
        name="id"
      />
      <Controller
        control={control}
        name="categories"
        rules={{
          validate: (value) => {
            const parsedCategories = Array.isArray(value)
              ? (value as CommonTransactionCategoryDto[])
              : [];

            if (!parsedCategories.length) {
              return t("_entities:transaction.category.required");
            }

            if (hasMixedTransactionCategoryTypes(parsedCategories)) {
              return t("_entities:transaction.category.required");
            }

            return true;
          },
        }}
        disabled={isLoading || lockCategory}
        render={({ field: { value, onChange, ...rest } }) => (
          <AutocompleteInput
            required
            options={categoryOptionsByType as Option[]}
            value={Array.isArray(value) ? value : []}
            onChange={(nextValue) =>
              onChange(
                normalizeSelectedTransactionCategories(
                  Array.isArray(nextValue)
                    ? (nextValue as CommonTransactionCategoryDto[])
                    : [],
                ),
              )
            }
            label={t("_entities:transaction.category.label")}
            placeholder={t("_entities:transaction.category.placeholder")}
            autoComplete={`${Tables.Transactions}-${t(
              "_entities:transaction.category.label",
            )}`}
            multiple
            {...rest}
          />
        )}
      />
      <Controller
        control={control}
        name="account"
        disabled={isLoading || lockAccount}
        render={({ field: { value, onChange, ...rest } }) => (
          <AutocompleteInput
            required
            options={accountOptions}
            value={value}
            onChange={(v) => onChange(v)}
            label={t("_entities:transaction.account.label")}
            autoComplete={`${Tables.Transactions}-${t(
              "_entities:transaction.account.label",
            )}`}
            multiple={false}
            {...rest}
          />
        )}
      />
      <Controller
        control={control}
        rules={{
          required: `${t("_entities:transaction.amount.required")}`,
        }}
        name="amount"
        disabled={isLoading}
        render={({ field: { value, ...rest } }) => (
          <TextInput
            required
            maxLength={20}
            value={value ?? ""}
            type="number"
            autoComplete={`${Tables.Transactions}-${t(
              "_entities:transaction.amount.label",
            )}`}
            label={t("_entities:transaction.amount.label")}
            placeholder={t("_entities:transaction.amount.placeholder")}
            {...rest}
          />
        )}
      />

      <Controller
        control={control}
        rules={{
          required: `${t("_entities:transaction.date.required")}`,
        }}
        name="date"
        disabled={isLoading}
        render={({ field: { value, ...rest } }) => (
          <TextInput
            required
            maxLength={20}
            value={value ?? ""}
            type="datetime-local"
            autoComplete={`${Tables.Transactions}-${t(
              "_entities:transaction.date.label",
            )}`}
            label={t("_entities:transaction.date.label")}
            placeholder={t("_entities:transaction.date.placeholder")}
            {...rest}
          />
        )}
      />
      <Controller
        control={control}
        name="description"
        disabled={isLoading}
        render={({ field: { value, ...rest } }) => (
          <ParagraphInput
            maxLength={60}
            value={value ?? ""}
            autoComplete={`${Tables.Transactions}-${t(
              "_entities:base.description.label",
            )}`}
            label={
              <span>
                {auto && <Autogenerated onlyIcon />}{" "}
                {t("_entities:base.description.label")}
              </span>
            }
            placeholder={t("_entities:base.description.placeholder")}
            {...rest}
          />
        )}
      />
    </>
  );
}

export function AddTransactionDialog(props: AddTransactionDialogPropsType) {
  return (
    <FormDialog {...props}>
      <TransactionForm {...props} />
    </FormDialog>
  );
}

export function EditTransactionDialog(props: EditTransactionDialogPropsType) {
  return (
    <FormDialog {...props}>
      <TransactionForm {...props} />
    </FormDialog>
  );
}
