import { useCallback, useEffect, useMemo, useRef } from "react";
import type { MouseEvent } from "react";
import { useTranslation } from "react-i18next";

// @sito/dashboard-app
import { classNames } from "@sito/dashboard-app";

// icons
import { faCircle, faCircleCheck } from "@fortawesome/free-solid-svg-icons";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";

// types
import type { TransactionCardPropsType } from "../types";

// views
import { Currency } from "views/Currencies/components/Currency";
import { Type } from "views/TransactionCategories/components/Type";

// lib
import {
  TransactionType,
  getPrimaryTransactionCategory,
  getTransactionCategories,
} from "lib";
import { useCalendarTimeAge } from "hooks/useCalendarTimeAge";

// components
import { SwipeToDelete } from "components";
import { Autogenerated } from "views/TransactionCategories";
import {
  getDeleteAction,
  shouldPreventMobileContextMenu,
} from "../../../components/Card/utils";

// styles
import "./styles.css";

export function TransactionCard(props: TransactionCardPropsType) {
  const { t } = useTranslation();

  const {
    id,
    onClick,
    onSelect,
    onLongPress,
    selectionMode,
    selected,
    description,
    auto,
    date,
    amount,
    account,
    deletedAt,
    actions,
    swipeDeleteOpen = false,
    onSwipeDelete,
  } = props;
  const deleted = !!deletedAt;
  const touchTimeoutRef = useRef<number | null>(null);
  const longPressTriggeredRef = useRef(false);

  const { timeAge } = useCalendarTimeAge();

  const deleteAction = useMemo(() => getDeleteAction(actions), [actions]);

  const parsedDescription = useMemo(() => {
    if (!description?.length) return t("_entities:base.description.empty");
    if (auto)
      return `${t("_entities:transactionCategory.description.init")}: ${description}`;
    return description;
  }, [description, auto, t]);

  const transactionCategories = useMemo(
    () => getTransactionCategories(props),
    [props],
  );

  const primaryCategory = useMemo(
    () => getPrimaryTransactionCategory(props),
    [props],
  );

  const hasAutogeneratedCategory = useMemo(
    () => transactionCategories.some((category) => category.auto),
    [transactionCategories],
  );

  const dateLabel = useMemo(() => {
    if (!date) return "";

    const parsedDate = new Date(date);

    if (Number.isNaN(parsedDate.getTime())) {
      return date;
    }

    return timeAge(parsedDate);
  }, [date, timeAge]);

  const parsedCategoryName = useMemo(() => {
    if (!transactionCategories.length) return "-";

    return transactionCategories
      .map((category) =>
        category.auto
          ? t("_entities:transactionCategory.name.init")
          : category.name,
      )
      .join(", ");
  }, [t, transactionCategories]);

  const clearTouchTimeout = useCallback(() => {
    if (touchTimeoutRef.current === null) return;
    window.clearTimeout(touchTimeoutRef.current);
    touchTimeoutRef.current = null;
  }, []);

  useEffect(() => {
    return () => {
      clearTouchTimeout();
    };
  }, [clearTouchTimeout]);

  const handleTouchStart = useCallback(() => {
    if (selectionMode || !onLongPress) return;

    clearTouchTimeout();
    touchTimeoutRef.current = window.setTimeout(() => {
      longPressTriggeredRef.current = true;
      onLongPress(id);
    }, 450);
  }, [clearTouchTimeout, id, onLongPress, selectionMode]);

  const handleClick = useCallback(() => {
    if (longPressTriggeredRef.current) {
      longPressTriggeredRef.current = false;
      return;
    }

    if (selectionMode) {
      onSelect?.(id);
      return;
    }

    if (deleted) return;

    onClick(id);
  }, [deleted, id, onClick, onSelect, selectionMode]);

  const handleContextMenu = useCallback(
    (event: MouseEvent<HTMLButtonElement>) => {
      if (!shouldPreventMobileContextMenu(!!onLongPress)) return;

      event.preventDefault();
    },
    [onLongPress],
  );

  return (
    <SwipeToDelete
      enabled={!!deleteAction && !!onSwipeDelete && !deleted && !selectionMode}
      deleteOpen={swipeDeleteOpen}
      onDeleteTrigger={() => onSwipeDelete?.()}
      onSwipeStart={clearTouchTimeout}
      shellClassName="rounded-lg"
      foregroundClassName="rounded-lg"
    >
      <button
        name={
          selectionMode
            ? t("_accessibility:components.table.selectRow")
            : t("_pages:transactions.forms.edit")
        }
        aria-label={
          selectionMode
            ? t("_accessibility:components.table.selectRow")
            : t("_pages:transactions.forms.editAria")
        }
        onClick={handleClick}
        onTouchStart={handleTouchStart}
        onTouchEnd={clearTouchTimeout}
        onTouchCancel={clearTouchTimeout}
        onTouchMove={clearTouchTimeout}
        onContextMenu={handleContextMenu}
        className={classNames(
          "transition",
          "transaction-card",
          deleted
            ? selectionMode && selected
              ? "transaction-card--deleted transaction-card--selected"
              : "transaction-card--deleted"
            : selectionMode
              ? selected
                ? "transaction-card--selected"
                : "transaction-card--selectable"
              : "transaction-card--idle",
        )}
        aria-pressed={selectionMode ? !!selected : undefined}
      >
        <Type
          className="transaction-card-type"
          type={primaryCategory?.type ?? TransactionType.In}
          filled={false}
          noText
        />
        <div className="transaction-card-body">
          <p
            className={classNames(
              "transaction-card-description",
              !description && "transaction-card-description--empty",
              deleted && "transaction-card-description--deleted",
            )}
          >
            {parsedDescription}
          </p>
          <div className="transaction-card-meta">
            {hasAutogeneratedCategory && <Autogenerated onlyIcon />}{" "}
            {parsedCategoryName}
            {dateLabel ? ` - ${dateLabel}` : ""}
          </div>
        </div>
        <p className="transaction-card-amount">
          {amount}{" "}
          <Currency
            name={account?.currency?.name}
            symbol={account?.currency?.symbol}
          />
        </p>
        {selectionMode ? (
          <span
            className={classNames(
              selected
                ? "transaction-card-selection-indicator--selected"
                : "transaction-card-selection-indicator--idle",
            )}
          >
            <FontAwesomeIcon icon={selected ? faCircleCheck : faCircle} />
          </span>
        ) : null}
      </button>
    </SwipeToDelete>
  );
}
