import { describe, it, expect, vi, afterEach } from "vitest";
import { act, fireEvent, render, screen } from "@testing-library/react";

vi.mock("react-i18next", () => ({
  useTranslation: () => ({
    t: (key: string) => key,
  }),
}));

vi.mock("@sito/dashboard-app", () => ({
  useTimeAge: () => ({
    timeAge: () => "1h",
  }),
}));

vi.mock("views/Currencies/components/Currency", () => ({
  Currency: ({ symbol }: { symbol?: string }) => <span>{symbol ?? ""}</span>,
}));

vi.mock("views/TransactionCategories/components/Type", () => ({
  Type: () => <span data-testid="transaction-type" />,
}));

vi.mock("views/TransactionCategories", () => ({
  Autogenerated: () => <span data-testid="autogenerated" />,
}));

vi.mock("lib", () => ({
  TransactionType: {
    Out: 0,
    In: 1,
  },
}));

import { TransactionCard } from "../TransactionCard";

const baseTransaction = {
  id: 42,
  description: "Coffee",
  auto: false,
  date: "2025-01-01T10:00:00.000Z",
  amount: 12.5,
  category: {
    id: 2,
    name: "Food",
    auto: false,
    type: 0,
    color: null,
    updatedAt: new Date("2025-01-01T10:00:00.000Z"),
  },
  account: {
    id: 1,
    name: "Wallet",
    updatedAt: new Date("2025-01-01T10:00:00.000Z"),
    currency: {
      id: 1,
      name: "EUR",
      symbol: "€",
      updatedAt: new Date("2025-01-01T10:00:00.000Z"),
    },
  },
  createdAt: new Date("2025-01-01T10:00:00.000Z"),
  updatedAt: new Date("2025-01-01T10:00:00.000Z"),
  deletedAt: null,
};

afterEach(() => {
  vi.useRealTimers();
});

describe("TransactionCard", () => {
  it("opens edit dialog on normal click", () => {
    const onClick = vi.fn();

    render(<TransactionCard {...baseTransaction} actions={[]} onClick={onClick} />);

    fireEvent.click(screen.getByRole("button"));

    expect(onClick).toHaveBeenCalledWith(42);
  });

  it("toggles selection instead of edit when selection mode is active", () => {
    const onClick = vi.fn();
    const onSelect = vi.fn();

    render(
      <TransactionCard
        {...baseTransaction}
        actions={[]}
        onClick={onClick}
        onSelect={onSelect}
        selectionMode
      />,
    );

    fireEvent.click(screen.getByRole("button"));

    expect(onSelect).toHaveBeenCalledWith(42);
    expect(onClick).not.toHaveBeenCalled();
  });

  it("starts selection mode on long press and prevents edit click", () => {
    vi.useFakeTimers();

    const onClick = vi.fn();
    const onLongPress = vi.fn();

    render(
      <TransactionCard
        {...baseTransaction}
        actions={[]}
        onClick={onClick}
        onLongPress={onLongPress}
      />,
    );

    const button = screen.getByRole("button");

    fireEvent.touchStart(button);
    act(() => {
      vi.advanceTimersByTime(500);
    });
    fireEvent.touchEnd(button);
    fireEvent.click(button);

    expect(onLongPress).toHaveBeenCalledWith(42);
    expect(onClick).not.toHaveBeenCalled();
  });
});
