import { describe, it, expect, vi, afterEach } from "vitest";
import {
  act,
  createEvent,
  fireEvent,
  render,
  screen,
} from "@testing-library/react";

let latestDragHandler:
  | ((state: {
      down: boolean;
      movement: [number, number];
      last: boolean;
      cancel: () => void;
    }) => void)
  | null = null;

vi.mock("@use-gesture/react", () => ({
  useDrag: (
    handler: (state: {
      down: boolean;
      movement: [number, number];
      last: boolean;
      cancel: () => void;
    }) => void,
  ) => {
    latestDragHandler = handler;
    return () => ({});
  },
}));

vi.mock("react-i18next", () => ({
  useTranslation: () => ({
    t: (key: string) => key,
  }),
}));

vi.mock("@sito/dashboard-app", () => ({
  classNames: (...classes: Array<string | false | null | undefined>) =>
    classes.filter(Boolean).join(" "),
  useTimeAge: () => ({
    timeAge: () => "1h",
  }),
}));

vi.mock("views/Currencies/components/Currency", () => ({
  Currency: ({ symbol }: { symbol?: string }) => <span>{symbol ?? ""}</span>,
}));

vi.mock("views/TransactionCategories/components/Type", () => ({
  Type: () => <span data-testid="transaction-type" />,
}));

vi.mock("views/TransactionCategories", () => ({
  Autogenerated: () => <span data-testid="autogenerated" />,
}));

vi.mock("lib", () => ({
  TransactionType: {
    Out: 0,
    In: 1,
  },
  getTransactionCategories: (transaction: {
    categories?: Array<{ id: number }>;
    category?: { id: number } | null;
  }) => {
    if (
      Array.isArray(transaction.categories) &&
      transaction.categories.length
    ) {
      return transaction.categories;
    }

    return transaction.category ? [transaction.category] : [];
  },
  getPrimaryTransactionCategory: (transaction: {
    categories?: Array<{ id: number }>;
    category?: { id: number } | null;
  }) => {
    if (
      Array.isArray(transaction.categories) &&
      transaction.categories.length
    ) {
      return transaction.categories[0];
    }

    return transaction.category ?? null;
  },
}));

import { TransactionCard } from "../TransactionCard";

const baseTransaction = {
  id: 42,
  description: "Coffee",
  auto: false,
  date: "2025-01-01T10:00:00.000Z",
  amount: 12.5,
  category: {
    id: 2,
    name: "Food",
    auto: false,
    type: 0,
    color: null,
    updatedAt: new Date("2025-01-01T10:00:00.000Z"),
  },
  account: {
    id: 1,
    name: "Wallet",
    updatedAt: new Date("2025-01-01T10:00:00.000Z"),
    currency: {
      id: 1,
      name: "EUR",
      symbol: "€",
      updatedAt: new Date("2025-01-01T10:00:00.000Z"),
    },
  },
  createdAt: new Date("2025-01-01T10:00:00.000Z"),
  updatedAt: new Date("2025-01-01T10:00:00.000Z"),
  deletedAt: null,
};

afterEach(() => {
  vi.useRealTimers();
  latestDragHandler = null;
  Object.defineProperty(window.navigator, "maxTouchPoints", {
    configurable: true,
    value: 0,
  });
});

describe("TransactionCard", () => {
  it("opens edit dialog on normal click", () => {
    const onClick = vi.fn();

    render(
      <TransactionCard {...baseTransaction} actions={[]} onClick={onClick} />,
    );

    fireEvent.click(screen.getByRole("button"));

    expect(onClick).toHaveBeenCalledWith(42);
  });

  it("toggles selection instead of edit when selection mode is active", () => {
    const onClick = vi.fn();
    const onSelect = vi.fn();

    render(
      <TransactionCard
        {...baseTransaction}
        actions={[]}
        onClick={onClick}
        onSelect={onSelect}
        selectionMode
      />,
    );

    fireEvent.click(screen.getByRole("button"));

    expect(onSelect).toHaveBeenCalledWith(42);
    expect(onClick).not.toHaveBeenCalled();
  });

  it("starts selection mode on long press and prevents edit click", () => {
    vi.useFakeTimers();

    const onClick = vi.fn();
    const onLongPress = vi.fn();

    render(
      <TransactionCard
        {...baseTransaction}
        actions={[]}
        onClick={onClick}
        onLongPress={onLongPress}
      />,
    );

    const button = screen.getByRole("button");

    fireEvent.touchStart(button);
    act(() => {
      vi.advanceTimersByTime(500);
    });
    fireEvent.touchEnd(button);
    fireEvent.click(button);

    expect(onLongPress).toHaveBeenCalledWith(42);
    expect(onClick).not.toHaveBeenCalled();
  });

  it("prevents the mobile context menu when long press selection is enabled", () => {
    Object.defineProperty(window.navigator, "maxTouchPoints", {
      configurable: true,
      value: 1,
    });

    render(
      <TransactionCard
        {...baseTransaction}
        actions={[]}
        onClick={() => undefined}
        onLongPress={() => undefined}
      />,
    );

    const button = screen.getByRole("button");
    const contextMenuEvent = createEvent.contextMenu(button);

    fireEvent(button, contextMenuEvent);

    expect(contextMenuEvent.defaultPrevented).toBe(true);
  });

  it("shows swipe delete affordance and triggers delete at 50% width", () => {
    Object.defineProperty(window.navigator, "maxTouchPoints", {
      configurable: true,
      value: 1,
    });

    const onDelete = vi.fn();

    render(
      <TransactionCard
        {...baseTransaction}
        actions={[
          {
            id: "delete",
            onClick: onDelete,
          },
        ]}
        onClick={() => undefined}
      />,
    );

    const button = screen.getByRole("button");
    const swipeShell = button.parentElement as HTMLDivElement;

    Object.defineProperty(swipeShell, "offsetWidth", {
      configurable: true,
      value: 100,
    });

    act(() => {
      latestDragHandler?.({
        down: true,
        movement: [40, 0],
        last: false,
        cancel: vi.fn(),
      });
    });

    expect(
      document.querySelector(".transaction-card-swipe-delete"),
    ).toHaveStyle({ width: "40px" });
    expect(onDelete).not.toHaveBeenCalled();

    act(() => {
      latestDragHandler?.({
        down: true,
        movement: [60, 0],
        last: false,
        cancel: vi.fn(),
      });
    });

    expect(onDelete).toHaveBeenCalledWith(
      expect.objectContaining({ id: baseTransaction.id }),
    );
  });
});
