import { useMemo } from "react";
import { useTranslation } from "react-i18next";

import { useCalendarTimeAge } from "hooks";
import {
  TransactionType,
  getPrimaryTransactionCategory,
  getTransactionCategories,
} from "lib";

import { Currency } from "views/Currencies/components/Currency";
import { Autogenerated, Type } from "views/TransactionCategories";

import type { RecentTransactionItemPropsType } from "./types";
import {
  getRecentTransactionAmountPrefix,
  isRecentTransactionIncome,
} from "./utils";

import "./styles.css";

export const RecentTransactionItem = (
  props: RecentTransactionItemPropsType,
) => {
  const { transaction } = props;
  const { t } = useTranslation();
  const { timeAge } = useCalendarTimeAge();

  const transactionCategories = useMemo(
    () => getTransactionCategories(transaction),
    [transaction],
  );

  const primaryCategory = useMemo(
    () => getPrimaryTransactionCategory(transaction),
    [transaction],
  );

  const parsedDescription = useMemo(() => {
    if (!transaction.description?.length) {
      return t("_entities:base.description.empty");
    }

    if (transaction.auto) {
      return t("_entities:transactionCategory.description.init");
    }

    return transaction.description;
  }, [t, transaction.auto, transaction.description]);

  const parsedCategoryName = useMemo(() => {
    if (!transactionCategories.length) return "-";

    return transactionCategories
      .map((category) =>
        category.auto
          ? t("_entities:transactionCategory.name.init")
          : category.name,
      )
      .join(", ");
  }, [t, transactionCategories]);

  const hasAutogeneratedCategory = useMemo(
    () => transactionCategories.some((category) => category.auto),
    [transactionCategories],
  );

  const dateLabel = useMemo(() => {
    if (!transaction.date) return "";

    const parsedDate = new Date(transaction.date);

    if (Number.isNaN(parsedDate.getTime())) {
      return transaction.date;
    }

    return timeAge(parsedDate);
  }, [timeAge, transaction.date]);

  const amountClassName = isRecentTransactionIncome(transaction)
    ? "recent-transaction-amount-value--income"
    : "recent-transaction-amount-value--expense";

  return (
    <li className="recent-transaction-item base-border">
      <Type
        className="recent-transaction-type"
        type={primaryCategory?.type ?? TransactionType.In}
        filled={false}
        noText
      />
      <div className="recent-transaction-body">
        <div className="recent-transaction-meta">
          {hasAutogeneratedCategory ? (
            <Autogenerated isTitle={false} />
          ) : (
            <p>{parsedCategoryName}</p>
          )}
          <p className="lowercase">{dateLabel ? `- ${dateLabel}` : ""}</p>
        </div>
        <p className="recent-transaction-description">{parsedDescription}</p>
      </div>
      <p className="recent-transaction-amount">
        <span className={amountClassName}>
          {getRecentTransactionAmountPrefix(transaction)}
          {transaction.amount}
        </span>
        <Currency
          name={transaction.account?.currency?.name}
          symbol={transaction.account?.currency?.symbol}
        />
      </p>
    </li>
  );
};
